CC=gcc
CFLAGS="-Wpedantic -Wall -Wextra -Werror -std=c89"

$CC $CFLAGS -c -fPIC doubll.c -o doubll.o
$CC $CFLAGS doubll.o -shared -o liblist.so

# liblist.so generated by the below command will be a non-PIC object file, i.e. not a shared library but a .o file
# $CC $CFLAGS -c doubll.c -shared -o liblist.so

$CC $CFLAGS -c test.c -o test.o
$CC $CFLAGS  -Wl,-rpath,$(pwd) test.o liblist.so -o dynamiclist
